import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setup(21,GPIO.OUT)
GPIO.setup(20,GPIO.OUT)
GPIO.setup(16,GPIO.OUT)
GPIO.setup(26,GPIO.OUT)
def intro():
    for i in range(0,2):
        GPIO.output(21,True)
        GPIO.output(20,False)
        GPIO.output(16,False)
        GPIO.output(26,False)
        time.sleep(0.25)
        GPIO.output(21,False)
        GPIO.output(20,True)
        GPIO.output(16,False)
        GPIO.output(26,False)
        time.sleep(0.25)
        GPIO.output(21,False)
        GPIO.output(20,False)
        GPIO.output(16,True)
        GPIO.output(26,False)
        time.sleep(0.25)
        GPIO.output(21,False)
        GPIO.output(20,False)
        GPIO.output(16,False)
        GPIO.output(26,True)
        time.sleep(0.25)
    GPIO.output(21,False)
    GPIO.output(20,False)
    GPIO.output(16,True)
    GPIO.output(26,True)
    time.sleep(0.5)
    GPIO.output(21,False)
    GPIO.output(20,True)
    GPIO.output(16,True)
    GPIO.output(26,True)
    time.sleep(0.5)
    GPIO.output(21,True)
    GPIO.output(20,True)
    GPIO.output(16,True)
    GPIO.output(26,True)
    
